---
- name: download remi repo
  get_url:
    url: "{{ remi_repo_url }}"
    dest: /tmp/remi-release-{{ ansible_distribution_major_version }}.rpm

- name: install remi repo
  package:
    name: /tmp/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present

- name: download remi gpg key
  get_url: url={{ remi_repo_gpg_key_url }} dest=/tmp/RPM-GPG-KEY-remi

- name: import remi gpg key
  rpm_key: key=/tmp/RPM-GPG-KEY-remi state=present
